### ISSUE TITLE
problem with npm

### ISSUE THREAD

**Issue by axel584** [viliusle/miniPaint#124]
Hi,
I'm trying to rebuild the dist/build.js file with : npm run dev
and I've this error message  : 

> C:\Program Files\apache-tomcat-8.5.27\webapps\bssmenu\minipaint>npm run dev
> npm ERR! missing script: dev
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\rousseaua\AppData\Roaming\npm-cache\_logs\2018-09-07T15_34_04_283Z-debug.log

The complete log is : 

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'dev' ]
> 2 info using npm@5.6.0
> 3 info using node@v9.8.0
> 4 verbose stack Error: missing script: dev
> 4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
> 4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
> 4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
> 4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
> 4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:357:45)
> 4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:400:3)
> 4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
> 4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
> 4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
> 4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
> 5 verbose cwd C:\Program Files\apache-tomcat-8.5.27\webapps\bssmenu\minipaint
> 6 verbose Windows_NT 10.0.15063
> 7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
> 8 verbose node v9.8.0
> 9 verbose npm  v5.6.0
> 10 error missing script: dev
> 11 verbose exit [ 1, true ]

I use npm 5.6.0.

Thank you for your help,

Axel

**Comment by axel584** [comment]
I try on another computer (wihout proxy) and I's work. 
It seem to be a proxy problem.
